[debug] [2024-03-21T19:28:29.418Z] ----------------------------------------------------------------------
[debug] [2024-03-21T19:28:29.423Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-03-21T19:28:29.424Z] CLI Version:   13.4.0
[debug] [2024-03-21T19:28:29.424Z] Platform:      win32
[debug] [2024-03-21T19:28:29.424Z] Node Version:  v18.17.0
[debug] [2024-03-21T19:28:29.426Z] Time:          Thu Mar 21 2024 16:28:29 GMT-0300 (Brasilia Standard Time)
[debug] [2024-03-21T19:28:29.427Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-03-21T19:28:29.433Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=636159857&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-03-21T19:28:46.601Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-03-21T19:28:46.601Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-03-21T19:28:46.809Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-03-21T19:28:46.809Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-03-21T19:28:50.727Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-03-21T19:28:50.729Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-03-21T19:29:07.667Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------438693723014281257345883","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c01::54:443
[debug] [2024-03-21T19:29:07.668Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\apiv2.js:246:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-03-21T19:29:07.708Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-03-21T19:29:07.708Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"87251ff0-7d9a-4722-b9f8-5e88a88914ae"}
[debug] [2024-03-21T19:29:07.868Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------848253738043031293743704","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c01::54:443
[debug] [2024-03-21T19:29:07.869Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\apiv2.js:246:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-03-21T19:29:29.201Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"87251ff0-7d9a-4722-b9f8-5e88a88914ae\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 2001:4860:4802:34::15:443
[debug] [2024-03-21T19:29:34.235Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-03-21T19:29:52.299Z] ----------------------------------------------------------------------
[debug] [2024-03-21T19:29:52.304Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-03-21T19:29:52.305Z] CLI Version:   13.4.0
[debug] [2024-03-21T19:29:52.305Z] Platform:      win32
[debug] [2024-03-21T19:29:52.306Z] Node Version:  v18.17.0
[debug] [2024-03-21T19:29:52.308Z] Time:          Thu Mar 21 2024 16:29:52 GMT-0300 (Brasilia Standard Time)
[debug] [2024-03-21T19:29:52.308Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-03-21T19:29:52.314Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=363904668&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-03-21T19:30:05.834Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-03-21T19:30:05.834Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-03-21T19:30:06.032Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-03-21T19:30:06.033Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-03-21T19:30:13.631Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-03-21T19:30:13.634Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-03-21T19:30:26.895Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------459621566805789402298200","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c01::54:443
[debug] [2024-03-21T19:30:26.896Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\apiv2.js:246:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-03-21T19:30:26.908Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-03-21T19:30:26.909Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"e3a6cf78-c599-4987-b026-0738c3dcabd5"}
[debug] [2024-03-21T19:30:27.098Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------355602030221175360404623","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c01::54:443
[debug] [2024-03-21T19:30:27.099Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\apiv2.js:246:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-03-21T19:30:47.975Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"e3a6cf78-c599-4987-b026-0738c3dcabd5\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 2001:4860:4802:34::15:443
[debug] [2024-03-21T19:30:52.998Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\joaot\AppData\Roaming\nvm\v18.17.0\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
